deploy:
  name: Manual Approval + Terraform Deploy
  runs-on: ubuntu-latest
  needs: ci-pipeline
  permissions:
    issues: write  # Required for manual-approval to work
  environment:
    name: production

  steps:
    - name: Manual Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: ginosettecasi  # Replace with your actual GitHub username
        minimum-approvals: 1
        timeout-minutes: 60

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
