name: Secure Edge Infrastructure CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci-pipeline:
    name: Lint, Validate, and Snyk Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install and Run Flake8
      run: |
        pip install flake8
        flake8 lambda/

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Format Check
      run: terraform fmt -check -recursive
      working-directory: terraform/

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/

    - name: Terraform Validate
      run: terraform validate
      working-directory: terraform/

    - name: Snyk Scan - IaC
      uses: snyk/actions/iac@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: test terraform/

    - name: Snyk Scan - Python
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: test lambda/

  deploy:
    name: Manual Approval + Terraform Deploy
    runs-on: ubuntu-latest
    needs: ci-pipeline
    environment:
      name: production
      url: https://your-site.com

    steps:
    - name: Manual Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: your-github-username
        instructions: "Approve to deploy edge security infra via Terraform."

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
